spring:
  h2.console:
      enabled: 'true'
      path: /console
  jpa:
    generate-ddl: 'true'
    hibernate:
      dll-auto: validate
  main:
    banner-mode: off
task.template.allowMultipleTasks: false
