spring:
  h2.console:
      enabled: 'true'
      path: /console
  jpa:
    generate-ddl: 'true'
    hibernate:
      dll-auto: update
  datasource:
    url: jdbc:h2:file:D:/PROGRAMMING/SPRING/udemy/todo-db
    username: sa
  main:
    banner-mode: off
task.template.allowMultipleTasks: false

