spring:
  h2.console:
      enabled: 'true'
      path: /console
  jpa:
    generate-ddl: 'true'
    hibernate:
      dll-auto: validate
  datasource:
    url: jdbc:h2:file:D:/PROGRAMMING/SPRING/udemy/todo-db
    username: sa
  main:
    banner-mode: off
management:
   endpoints:
     web:
       exposure:
         include: '*'
task.template.allowMultipleTasks: false
keycloak:
  auth-server-url: 'http://localhost:8180/auth'
  realm: 'TodoApp'
  resource: 'todo-spring-client'
  public-client: true


